-- Gerado por scripts/build_sports_seed.py. Não edite à mão.
-- 134 esportes.
insert into public.sports (slug, name, category) values
  ('futebol', 'Futebol', 'coletivo'),
  ('futsal', 'Futsal', 'coletivo'),
  ('futebol-society', 'Futebol Society', 'coletivo'),
  ('futevolei', 'Futevôlei', 'coletivo'),
  ('basquete', 'Basquete', 'coletivo'),
  ('volei', 'Vôlei', 'coletivo'),
  ('volei-de-praia', 'Vôlei de Praia', 'coletivo'),
  ('handebol', 'Handebol', 'coletivo'),
  ('rugby', 'Rugby', 'coletivo'),
  ('futebol-americano', 'Futebol Americano', 'coletivo'),
  ('beisebol', 'Beisebol', 'coletivo'),
  ('hoquei-sobre-patins', 'Hóquei sobre Patins', 'coletivo'),
  ('hoquei-no-gelo', 'Hóquei no Gelo', 'coletivo'),
  ('polo-aquatico', 'Polo Aquático', 'coletivo'),
  ('queimada', 'Queimada', 'coletivo'),
  ('pique-bandeira', 'Pique-bandeira', 'coletivo'),
  ('taco', 'Taco', 'coletivo'),
  ('frisbee', 'Frisbee', 'coletivo'),
  ('tenis', 'Tênis', 'raquete'),
  ('beach-tennis', 'Beach Tennis', 'raquete'),
  ('padel', 'Padel', 'raquete'),
  ('tenis-de-mesa', 'Tênis de Mesa', 'raquete'),
  ('badminton', 'Badminton', 'raquete'),
  ('squash', 'Squash', 'raquete'),
  ('frescobol', 'Frescobol', 'raquete'),
  ('peteca', 'Peteca', 'raquete'),
  ('corrida', 'Corrida', 'corrida e ciclismo'),
  ('maratona', 'Maratona', 'corrida e ciclismo'),
  ('atletismo', 'Atletismo', 'corrida e ciclismo'),
  ('trekking', 'Trekking', 'corrida e ciclismo'),
  ('trilha', 'Trilha', 'corrida e ciclismo'),
  ('ciclismo', 'Ciclismo', 'corrida e ciclismo'),
  ('mountain-bike', 'Mountain Bike', 'corrida e ciclismo'),
  ('bike-bmx', 'Bike BMX', 'corrida e ciclismo'),
  ('bike-freestyle', 'Bike Freestyle', 'corrida e ciclismo'),
  ('triatlo', 'Triatlo', 'corrida e ciclismo'),
  ('natacao', 'Natação', 'aquático'),
  ('nado-sincronizado', 'Nado Sincronizado', 'aquático'),
  ('surf', 'Surf', 'aquático'),
  ('bodyboard', 'Bodyboard', 'aquático'),
  ('kitesurf', 'Kitesurf', 'aquático'),
  ('windsurf', 'Windsurf', 'aquático'),
  ('stand-up-paddle', 'Stand Up Paddle', 'aquático'),
  ('canoagem', 'Canoagem', 'aquático'),
  ('remo', 'Remo', 'aquático'),
  ('rafting', 'Rafting', 'aquático'),
  ('iatismo', 'Iatismo', 'aquático'),
  ('wakeboard', 'Wakeboard', 'aquático'),
  ('esqui-aquatico', 'Esqui Aquático', 'aquático'),
  ('jet-ski', 'Jet Ski', 'aquático'),
  ('flyboard', 'Flyboard', 'aquático'),
  ('mergulho-apneia', 'Mergulho Apneia', 'aquático'),
  ('mergulho-com-cilindro', 'Mergulho com Cilindro', 'aquático'),
  ('snorkel', 'Snorkel', 'aquático'),
  ('salto-ornamental', 'Salto Ornamental', 'aquático'),
  ('pesca-esportiva', 'Pesca Esportiva', 'aquático'),
  ('boxe', 'Boxe', 'luta'),
  ('muay-thai', 'Muay Thai', 'luta'),
  ('mma', 'MMA', 'luta'),
  ('jiu-jitsu', 'Jiu-Jitsu', 'luta'),
  ('judo', 'Judô', 'luta'),
  ('karate', 'Karatê', 'luta'),
  ('taekwondo', 'Taekwondo', 'luta'),
  ('kung-fu', 'Kung Fu', 'luta'),
  ('capoeira', 'Capoeira', 'luta'),
  ('aikido', 'Aikido', 'luta'),
  ('hapkido', 'Hapkido', 'luta'),
  ('kendo', 'Kendô', 'luta'),
  ('krav-maga', 'Krav Maga', 'luta'),
  ('kali-filipino', 'Kali Filipino', 'luta'),
  ('luta-livre', 'Luta Livre', 'luta'),
  ('luta-greco-romana', 'Luta Greco-romana', 'luta'),
  ('full-contact', 'Full Contact', 'luta'),
  ('body-combat', 'Body Combat', 'luta'),
  ('esgrima', 'Esgrima', 'luta'),
  ('sumo', 'Sumô', 'luta'),
  ('queda-de-braco', 'Queda de Braço', 'luta'),
  ('funcional', 'Funcional', 'fitness'),
  ('crossfit', 'Crossfit', 'fitness'),
  ('musculacao', 'Musculação', 'fitness'),
  ('halterofilismo', 'Halterofilismo', 'fitness'),
  ('fisiculturismo', 'Fisiculturismo', 'fitness'),
  ('pilates', 'Pilates', 'fitness'),
  ('yoga', 'Yoga', 'fitness'),
  ('tai-chi-chuan', 'Tai Chi Chuan', 'fitness'),
  ('ginastica', 'Ginástica', 'fitness'),
  ('ginastica-artistica', 'Ginástica Artística', 'fitness'),
  ('ginastica-ritmica', 'Ginástica Rítmica', 'fitness'),
  ('ginastica-natural', 'Ginástica Natural', 'fitness'),
  ('danca', 'Dança', 'fitness'),
  ('skate-street', 'Skate Street', 'radical'),
  ('skate-vertical', 'Skate Vertical', 'radical'),
  ('skate-downhill', 'Skate Downhill', 'radical'),
  ('skate-freestyle', 'Skate Freestyle', 'radical'),
  ('patins', 'Patins', 'radical'),
  ('patinacao-artistica', 'Patinação Artística', 'radical'),
  ('parkour', 'Parkour', 'radical'),
  ('slackline', 'Slackline', 'radical'),
  ('escalada', 'Escalada', 'radical'),
  ('rapel', 'Rapel', 'radical'),
  ('montanhismo', 'Montanhismo', 'radical'),
  ('alpinismo', 'Alpinismo', 'radical'),
  ('espeleologia', 'Espeleologia', 'radical'),
  ('paraquedismo', 'Paraquedismo', 'radical'),
  ('parapente', 'Parapente', 'radical'),
  ('asa-delta', 'Asa Delta', 'radical'),
  ('voo-livre', 'Voo Livre', 'radical'),
  ('balonismo', 'Balonismo', 'radical'),
  ('esqui-na-neve', 'Esqui na Neve', 'radical'),
  ('malabarismo', 'Malabarismo', 'radical'),
  ('kart', 'Kart', 'motor'),
  ('automobilismo', 'Automobilismo', 'motor'),
  ('motocross', 'Motocross', 'motor'),
  ('motovelocidade', 'Motovelocidade', 'motor'),
  ('enduro', 'Enduro', 'motor'),
  ('trilha-4x4', 'Trilha 4x4', 'motor'),
  ('arco-e-flecha', 'Arco e Flecha', 'precisão'),
  ('tiro-esportivo', 'Tiro Esportivo', 'precisão'),
  ('dardos', 'Dardos', 'precisão'),
  ('golfe', 'Golfe', 'precisão'),
  ('bocha', 'Bocha', 'precisão'),
  ('boliche', 'Boliche', 'precisão'),
  ('sinuca', 'Sinuca', 'precisão'),
  ('bumerangue', 'Bumerangue', 'precisão'),
  ('airsoft', 'Airsoft', 'precisão'),
  ('paintball', 'Paintball', 'precisão'),
  ('xadrez', 'Xadrez', 'mente'),
  ('jogos-de-cartas', 'Jogos de Cartas', 'mente'),
  ('e-sports', 'E-sports', 'mente'),
  ('hipismo', 'Hipismo', 'equestre'),
  ('polo-a-cavalo', 'Polo a Cavalo', 'equestre'),
  ('laco', 'Laço', 'equestre'),
  ('esportes-caninos', 'Esportes Caninos', 'outros'),
  ('jogos-medievais', 'Jogos Medievais', 'outros')
on conflict (slug) do update set name = excluded.name, category = excluded.category;
