/**
 * Todos os textos do Riff ficam aqui, para a voz ficar consistente.
 * Voz: frases curtas, segunda pessoa, bem-humorada sem forçar.
 * Nunca culpar a pessoa, principalmente em falta e penalidade.
 */
export const copy = {
  app: {
    name: 'Riff Sports',
    tagline: 'Tecnologia a favor do esporte',
  },
  nav: {
    eventos: 'Eventos',
    jogar: 'Jogar',
    perfil: 'Perfil',
  },
  empty: {
    eventos: 'Ainda não tem jogo por aqui. Bora criar o primeiro?',
    jogar: 'Logo, logo você acha uma galera pra jogar.',
    perfil: 'Seu perfil vai morar aqui.',
  },
  actions: {
    join: 'Tô dentro',
    retry: 'Tentar de novo',
    back: 'Voltar',
    continue: 'Continuar',
    save: 'salvar',
    loading: 'Carregando...',
  },
  event: {
    full: 'Lotou! Quer entrar na fila? Se alguém sair, a vaga é sua.',
    created: 'Pronto, tá no ar! Manda o link pra galera.',
    noShow: 'Hoje não rolou, acontece. Seu Score ajusta e é só aparecer no próximo.',
  },
  errors: {
    network: 'Não consegui salvar agora. Tenta de novo?',
    notFound: 'Essa quadra não existe. Bora voltar pro jogo?',
    generic: 'Algo saiu do esquema. Tenta de novo?',
  },
  welcome: {
    signUp: 'Criar uma conta',
    signIn: 'Iniciar sessão',
  },
  auth: {
    fields: {
      name: 'Nome:',
      email: 'E-mail:',
      password: 'Senha:',
      confirmPassword: 'Confirmar Senha:',
      newPassword: 'Nova senha:',
      showPassword: 'Mostrar senha',
      hidePassword: 'Esconder senha',
    },
    signUp: {
      title: 'Boas-vindas à Riff!',
      subtitle: 'Como você gostaria de se cadastrar?',
      submit: 'Aceitar e cadastrar',
      consentPrefix: 'Ao cadastrar, você aceita os ',
      terms: 'Termos de Uso',
      consentMiddle: ' e a ',
      privacy: 'Política de Privacidade',
      hasAccount: 'Já tem uma conta? Faça login',
    },
    checkEmail: {
      title: 'Confere seu e-mail.',
      body: 'Mandamos um link de confirmação. É só tocar nele pra continuar o cadastro.',
      hint: 'Não chegou? Dá uma olhada no spam ou na aba promoções.',
      backToLogin: 'Já confirmei, quero entrar',
    },
    signIn: {
      title: 'Bem-vindo de volta.',
      subtitle: 'Entre, e jogue o que quiser.',
      forgot: 'Esqueci a senha',
      submit: 'Entrar',
      noAccount: 'Não possui uma conta?',
    },
    forgot: {
      title: 'Esqueceu a senha?',
      subtitle: 'Acontece. Manda seu e-mail que a gente te ajuda.',
      submit: 'Enviar link',
      sent: 'Se esse e-mail tiver conta no Riff, o link já tá a caminho.',
      backToLogin: 'Voltar pro login',
    },
    reset: {
      title: 'Bora de senha nova.',
      subtitle: 'Escolhe uma que você lembre, mas que ninguém adivinhe.',
      submit: 'Salvar senha',
      done: 'Senha trocada! Agora é só jogar.',
      expired: 'Esse link expirou. Pede um novo?',
      requestNew: 'Pedir novo link',
    },
    validation: {
      nameRequired: 'Conta pra gente seu nome.',
      emailInvalid: 'Esse e-mail parece incompleto.',
      passwordMin: 'A senha precisa de pelo menos 8 caracteres.',
      passwordLettersDigits: 'Mistura letras e números na senha.',
      passwordMismatch: 'As senhas não bateram.',
      passwordRequired: 'Falta a senha.',
    },
    errors: {
      invalidCredentials: 'E-mail ou senha não bateram. Confere e tenta de novo?',
      emailNotConfirmed: 'Falta confirmar seu e-mail. Dá uma olhada na caixa de entrada.',
      userExists: 'Esse e-mail já tem conta. Bora fazer login?',
      weakPassword: 'Essa senha tá fácil demais. Tenta uma mais forte?',
      rateLimit: 'Muitas tentativas seguidas. Espera um minutinho e tenta de novo.',
    },
    signOut: 'Sair da conta',
  },
  onboarding: {
    stepOf: (step: number, total: number) => `Passo ${step} de ${total}`,
    privacyNote:
      'Coletamos suas informações para facilitar a geração de uma equipe. Seus dados são mantidos seguros.',
    step1: {
      title: 'Fale um pouquinho sobre você.',
      photo: 'Envie uma foto sua',
      photoButton: 'Imagem do perfil',
      photoChange: 'Trocar foto',
      fullName: 'Qual seu nome completo?',
      fullNamePlaceholder: 'Nome',
      birthDate: 'Qual sua data de nascimento?',
      birthDatePlaceholder: 'Data de nascimento',
      displayName: 'Como gostaria de ser chamado?',
      displayNamePlaceholder: 'Nome de preferência',
    },
    step2: {
      title: 'Não falta muito.',
      accessibility: 'Você possui alguma necessidade de acessibilidade?',
      accessibilityPlaceholder: 'Acessibilidade',
      gender: 'Indique seu gênero',
      finish: 'Concluir',
    },
    validation: {
      fullNameMin: 'Coloca nome e sobrenome.',
      birthDateRequired: 'Falta a data de nascimento.',
      underage: 'O Riff é para maiores de 18 anos. Te esperamos quando chegar lá!',
      birthDateInvalid: 'Essa data não parece certa.',
      accessibilityRequired: 'Escolhe uma opção (pode ser "Nenhuma").',
      genderRequired: 'Escolhe uma opção.',
      photoTooBig: 'Essa foto passou de 5 MB. Tenta uma menor?',
      photoType: 'Use uma foto JPG, PNG ou WEBP.',
    },
    done: 'Pronto, tá no time!',
  },
  profile: {
    memberSince: (date: string) => `Membro desde ${date}`,
    eventsJoined: (count: number) => `Eventos que participou: ${count}`,
    instagram: 'Instagram',
    edit: 'Editar perfil',
    editTitle: 'Editar perfil',
    noBio: 'Ainda sem bio. Conta pra galera que tipo de jogador você é.',
    fields: {
      fullName: 'Nome',
      displayName: 'Como gostaria de ser chamado',
      bio: 'Bio',
      instagram: 'Instagram',
      instagramPlaceholder: 'seu.usuario',
      photo: 'Trocar foto do perfil',
    },
    validation: {
      bioMax: 'A bio vai até 500 caracteres.',
      instagramInvalid: 'Use só letras, números, ponto e sublinhado.',
      displayNameMax: 'Até 40 caracteres.',
    },
    saved: 'Perfil atualizado!',
    notFound: 'Não achei esse jogador. Pode ter saído do Riff.',
  },
  options: {
    gender: {
      masculino: 'Masculino',
      feminino: 'Feminino',
      nao_binario: 'Não binário',
      prefiro_nao_informar: 'Prefiro não informar',
    },
    accessibility: {
      nenhuma: 'Nenhuma',
      mobilidade_reduzida: 'Mobilidade reduzida',
      cadeirante: 'Uso cadeira de rodas',
      visual: 'Deficiência visual',
      auditiva: 'Deficiência auditiva',
      intelectual: 'Deficiência intelectual',
      outra: 'Outra',
    },
  },
  legal: {
    termsTitle: 'Termos de Uso',
    privacyTitle: 'Política de Privacidade',
    draft:
      'Versão provisória para o piloto fechado. O texto final será publicado antes da abertura ao público.',
  },
} as const
